name: Build and Test Services

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Show current working directory
        run: pwd  # Покажет текущую директорию

      - name: List files in the current directory
        run: ls -la  # Выведет все файлы и папки в текущей директории

      - name: Try to list ESND folder
        run: |
          if [ -d "ESND" ]; then
            echo "ESND directory exists!"
            ls -la ESND
          else
            echo "ESND directory does not exist!"
          fi   

      - name: Build and run services with Docker Compose
        run: |
          docker-compose up -d --build

      - name: Wait for services to start
        run: |
          timeout=60
          while [ $timeout -gt 0 ]; do
            if docker-compose ps | grep -q 'Up'; then
              echo "All services are up!"
              break
            fi
            echo "Waiting for services to start..."
            sleep 5
            timeout=$((timeout - 5))
          done
          if [ $timeout -le 0 ]; then
            echo "Timeout waiting for services to start!"
            exit 1
          fi

      - name: Check services health
        run: |
          # Здесь вы можете добавить команды для проверки работоспособности
          # например, проверка статуса HTTP с помощью curl
          # curl -f http://localhost:YOUR_PORT/health || exit 1
          echo "Services are running correctly."