name: Update Submodule

on:
  push:
    branches:
      - main

jobs:
  update-submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Update user service submodule
        run: |
          cd user-service
          git checkout main
          git pull origin main 
          cd ..

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "myakkaynt228@gmail.com"
          git config --global user.name "aidar"
          git add user-service
          git commit -m "Update user-service submodule" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/AidarKhaibulov/ESND.git HEAD:main