name: Build and Test Services

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Initialize and update submodules
        run: |
          git submodule init
          git submodule update --recursive --remote

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build user-service
        run: |
          cd user-service
          ./gradlew wrapper --gradle-version 8.5  # Обновляем до Gradle 8.5
          ./gradlew build

      - name: Build order-service
        run: |
          cd order-service
          ./gradlew wrapper --gradle-version 8.5  # Обновляем до Gradle 8.5
          ./gradlew build  # Собираем проект

      - name: Setup Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run services with Docker Compose
        run: |
          docker-compose up -d --build

      - name: Wait for services to start
        run: |
          timeout=60
          while [ $timeout -gt 0 ]; do
            if docker-compose ps | grep -q 'Up'; then
              echo "All services are up!"
              break
            fi
            echo "Waiting for services to start..."
            sleep 5
            timeout=$((timeout - 5))
          done
          if [ $timeout -le 0 ]; then
            echo "Timeout waiting for services to start!"
            exit 1
          fi

      - name: Check services health
        run: |
          echo "Services are running correctly."