name: Update Main Repo

on:
  push:
    branches:
      - main  # Укажите вашу ветку, если это другая ветка

jobs:
  update-main-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout user-service
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout main repo
        run: |
          git clone git@github.com:AidarKhaibulov/ESND.git main-repo
          cd main-repo
          git checkout main 

      - name: Update submodule
        run: |
          cd main-repo
          git submodule update --init --recursive
          git add user-service
          git commit -m "Обновлен подмодуль user-service" || exit 0
          git push