name: Update Main Repo

on:
  push:
    branches:
      - main

jobs:
  update-main-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout user-service
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Configure Git
        run: |
          git config --global user.email "myakkaynt228@gmail.com"
          git config --global user.name "aidar"

      - name: Checkout main repo
        run: |
          git clone git@github.com:AidarKhaibulov/ESND.git main-repo
          cd main-repo
          git checkout main 

      - name: Initialize and update submodules
        run: |
          cd main-repo
          git submodule init
          git submodule update

      - name: Update user-service submodule to latest commit
        run: |
          cd main-repo
          git submodule update --remote user-service
          git add user-service
          git commit -m "Update user-service" || exit 0
          git push

      - name: Update order-service submodule to latest commit
        run: |
          cd main-repo
          git submodule update --remote order-service
          git add order-service
          git commit -m "Update order-service" || exit 0
          git push